### ISSUE TITLE
A variavel Log não foi instanciada 

### ISSUE THREAD

**Issue by vitorPagHiper** [henriqueccruz/woocommerce-paghiper#1]
https://github.com/henriqueccruz/woocommerce-paghiper/blob/a699231edb4ef592e675fd9a5fe1dc86b07e49f6/includes/wc-paghiper-notification.php#L130

Ao gerar um pedido recebemos um warning, acusando que nao foi definida.

**Comment by henriqueccruz** [comment]
Abordado no commit [#2f1e05d](https://github.com/henriqueccruz/woocommerce-paghiper/commit/2f1e05df71f62afd25e70f52f0fbf0bddb4f2003)
